### PR TITLE
Rework commitments

### PR DESCRIPTION
**Pull request by JanBobolz**
Reworked the commitment interfaces and Pedersen commitments.

Must merge the `expr-opt` branch into `math` first.

### CODE REVIEW

**Comment by JanBobolz** [comment]
@rheitjoh can you please merge the expression stuff and then this?

**Comment by feidens** [comment]
> @rheitjoh can you please merge the expression stuff and then this? (As soon as it's convenient - no need for a huge hurry, though)

Is this till ongoing?

**Comment by rheitjoh** [comment]
math isn't getting merged any time soon due to the rewrite so we should merge anyway

**Comment by feidens** [comment]
> math isn't getting merged any time soon due to the rewrite so we should merge anyway

@JanBobolz maybe you added something that depends on the new math stuff?

**Comment by rheitjoh** [comment]
There is some code that uses the new expressions. But the new things on craco master already use that anyway.

**Comment by JanBobolz** [comment]
> @JanBobolz maybe you added something that depends on the new math stuff?

This branch currently depends on the old version of the expressions. When the whole rework stuff is done, it shouldn't use expressions at all anymore, I think. We can merge this after the big rework, I'd say

**Comment by JanBobolz** [comment]
Why https://github.com/upbcuk/upb.crypto.craco/pull/10/commits/90878b5b9c3a811147079c4aab5b3b66f4dbc219 ? https://discuss.gradle.org/t/best-practice-for-gradle-properties-and-scm/5809/4

**Review by rheitjoh — APPROVED** [review]

**Review by rheitjoh — APPROVED** [review]

**Pull request merged**
